### ISSUE TITLE
100 vh on mobile devices

### ISSUE THREAD

**Issue by zw627** [zw627/journey-towards-enlightenment#15]
`100 vh` does not display properly on mobile devices.

**Comment by zw627** [comment]
## Cause

Navigation and URL bars.

## Solution

```CSS
.my-element {
  height: 100vh; /* Fallback for browsers that do not support Custom Properties */
  height: calc(var(--vh, 1vh) * 100);
}
```

```JavaScript
// First we get the viewport height and we multiple it by 1% to get a value for a vh unit
let vh = window.innerHeight * 0.01;
// Then we set the value in the --vh custom property to the root of the document
document.documentElement.style.setProperty("--vh", `${vh}px`);

window.addEventListener("resize", () => {
  let vh = window.innerHeight * 0.01;
  document.documentElement.style.setProperty("--vh", `${vh}px`);
});
```

Reference: https://css-tricks.com/the-trick-to-viewport-units-on-mobile/
